force-app/main/default/objects/Prospect__c/Prospect__c.object-meta.xml
<CustomObject>
    <description>Piste de recrutement Scouting 360.</description>
    <label>Prospect</label>
    <nameField>
        <label>Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prospect__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <description>Identifiant externe unique du prospect.</description>
    <externalId>true</externalId>
    <fullName>ExternalId__c</fullName>
    <label>External ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SC360ScoutingProspectEnrichBatch.cls
/**
 * Batch 1-by-1 : 1 prospect APISPORTS-* = 1 callout (limite Salesforce).
 */
public class SC360ScoutingProspectEnrichBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    private final Integer seasonYear;

    public SC360ScoutingProspectEnrichBatch(Integer seasonYear) {
        this.seasonYear = seasonYear != null ? seasonYear : SC360ScoutingProspectSyncService.DEFAULT_SEASON;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [SELECT Id, ExternalId__c FROM Prospect__c WHERE ExternalId__c LIKE 'APISPORTS-%']
        );
    }

    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        for (sObject row : scope) {
            try {
                SC360ScoutingProspectSyncService.enrichProspectFromRecord((Prospect__c) row, seasonYear);
            } catch (Exception e) {
                System.debug(LoggingLevel.WARN, 'Scouting enrich ' + row.Id + ' : ' + e.getMessage());
            }
        }
    }

    public void finish(Database.BatchableContext bc) {
    }
}